# frozen_string_literal: true

require "json"
require "net/http"
require "uri"

# Shared only by Google-auth request specs. It deliberately stubs the two
# network/verification boundaries used by AdminAuth; every controller, cookie,
# and database operation continues through the real Rails application.
module GoogleOauthHelpers
  def oauth_env
    {
      "PUBLIC_BASE_URL" => "https://event.example",
      "ADMIN_FRONTEND_URL" => "https://event.example/admin",
      "GOOGLE_OAUTH_CALLBACK_URL" => "https://event.example/api/auth/google/callback",
      "GOOGLE_CLIENT_ID" => "test-client.apps.googleusercontent.com",
      "GOOGLE_CLIENT_SECRET" => "test-client-secret",
      "ADMIN_EMAIL_ALLOWLIST" => "environment@example.com"
    }
  end

  def new_browser
    open_session.tap do |browser|
      browser.host! "event.example"
      browser.https!
    end
  end

  def start_google_oauth(browser)
    browser.get "/api/auth/google/start"
    expect(browser.response).to have_http_status(:found)

    URI.decode_www_form(URI.parse(browser.response.headers.fetch("Location")).query).to_h.fetch("state")
  end

  def complete_google_oauth(browser, state:, code:)
    browser.get "/api/auth/google/callback", params: { code:, state: }
  end

  def google_claims(state:, email:, sub:)
    {
      "email" => email,
      "email_verified" => true,
      "sub" => sub,
      "nonce" => state
    }
  end

  def google_token_response(id_token: "signed-id-token")
    Net::HTTPOK.new("1.1", "200", "OK").tap do |token_response|
      token_response.instance_variable_set(
        :@body,
        JSON.generate(id_token:, access_token: "google-access-token")
      )
      token_response.instance_variable_set(:@read, true)
    end
  end

  # No real Google request can occur: the token endpoint and ID-token verifier
  # must each receive exactly the request generated by AdminAuth.
  def expect_google_exchange(code:, claims:, id_token: "signed-id-token")
    expect(Net::HTTP).to receive(:post_form).with(
      URI("https://oauth2.googleapis.com/token"),
      code:,
      client_id: oauth_env.fetch("GOOGLE_CLIENT_ID"),
      client_secret: oauth_env.fetch("GOOGLE_CLIENT_SECRET"),
      redirect_uri: oauth_env.fetch("GOOGLE_OAUTH_CALLBACK_URL"),
      grant_type: "authorization_code"
    ).and_return(google_token_response(id_token:))
    expect(Google::Auth::IDTokens).to receive(:verify_oidc)
      .with(id_token, aud: oauth_env.fetch("GOOGLE_CLIENT_ID"))
      .and_return(claims)
  end

  def google_login(browser, email:, sub:, code:)
    state = start_google_oauth(browser)
    expect_google_exchange(code:, claims: google_claims(state:, email:, sub:))
    complete_google_oauth(browser, state:, code:)
    expect(browser.response).to have_http_status(:found)
    expect(browser.response.headers.fetch("Location")).to eq(oauth_env.fetch("ADMIN_FRONTEND_URL"))
    state
  end

  def response_json(browser)
    browser.response.parsed_body
  end

  def same_origin_headers
    { "Origin" => oauth_env.fetch("PUBLIC_BASE_URL") }
  end
end
