default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"].to_s.empty? ? "nil" : ENV["DATABASE_URL"].inspect %>

development:
  primary:
    <<: *default
    database: anabuki_event_rails_development
    username: <%= ENV.fetch("POSTGRES_USER", "anabuki") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "anabuki") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

test:
  primary:
    <<: *default
    database: anabuki_event_rails_test
    username: <%= ENV.fetch("POSTGRES_USER", "anabuki") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "anabuki") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "anabuki_event_rails_production") %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV["POSTGRES_HOST"] %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
